on:
  pull_request:
    types: [opened, reopened]
name: Assign Reviewers
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Mikeal Rogers
      uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
      if: contains(fromJSON('["mikeal"]'), github.event.pull_request.user.login)
      with:
        reviewers: "mikeal"
        token: ${{ secrets.GITHUB_TOKEN }}  
